package com.soundgram.chipster.domain.model

data class PackInfo(
    val allCardSize: Int? = 0,
    val cardImg: String? = "",
    val cardMotionImg: String,
    val codeKey: String,
    val commentSize: Int? = 0,
    val content: String,
    val endTime: String,
    val getMotionImg: String,
    val img: String,
    val level1Msg: String,
    val level2Msg: String,
    val level3Msg: String,
    val level4Msg: String,
    val level5Msg: String,
    val makerUserNickName: String? = "",
    val music: Any,
    val name: String,
    val packId: Int,
    val packStatus: Int,
    val packType: Int,
    val pinDoneImg: String,
    val pinImg: String,
    val pocaList: Any,
    val pocaSize: Any,
    val registerTime: String,
    val representPocaAddress: Any,
    val startTime: String,
    val targetImg: String,
    val timestamp: String,
    val totType: Int,
    val totalPocaSize: Any,
    val updateTime: String,
    val userSize: Any
)